### PR TITLE
Fix compile: make char *updateparams const.

### PR DESCRIPTION
**Pull request by hzeller**
* The writable strings won't compile these days anymore; make `char *updateparams` -> `const char *updateparams`.
  * While at it: fix instance variable initialization to be the same order as field declaration.
  * Makefile: it is common to use CXX as the variable holding a c++ compiler.

### CODE REVIEW

File: RRDatabase.cpp [hunk 1]
```diff
@@ -24,7 +24,7 @@ int RRDatabase::update(time_t time, double counter) {
     char values[256];
     snprintf(values, 255, "%ld:%.1f:%.0f", (long)time, counter/*kWh*/, counter * 3600000. /*Ws*/);
 
-    char *updateparams[] = { "rrdupdate", _filename, values, NULL };
+    const char *updateparams[] = { "rrdupdate", _filename, values, NULL };
```
Comment (skaringa) [inline RRDatabase.cpp]: This doesn't compile with my setup based on Ubuntu LTS 24.04 which is using librrd-dev:amd64 1.7.2-4.1ubuntu3:

`
RDatabase.cpp: In member function ‘int RRDatabase::update(time_t, double)’:
RRDatabase.cpp:30:29: error: invalid conversion from ‘const char**’ to ‘char**’ [-fpermissive]
   30 |     int res = rrd_update(3, updateparams);
      |                             ^~~~~~~~~~~~
      |                             |
      |                             const char**
In file included from RRDatabase.cpp:6:
/usr/include/rrd.h:174:5: note:   initializing argument 2 of ‘int rrd_update(int, char**)’
`

**Comment by skaringa** [comment]
This fix would require rrdtool 1.9 which is still not available for Ubuntu LTS (has librrd-dev 1.7.2) nor Debian stable.
